### PR TITLE
last update to paper details for second preprint & submission

### PR DESCRIPTION
**Pull request by ctb**

### CODE REVIEW

**Comment by ctb** [comment]
This is now mostly baked; just waiting to verify / fix binder stuff.

@taylorreiter could you add a few wise words to the README in `pipeline-analyses/` about what the different pipelines do? Could directly refer to your beautiful DAG in the appendix.

**Comment by taylorreiter** [comment]
@ctb There are READMEs in each subfolder of pipeline analyses that layout what each workflow does...would you like this organized differently?

**Comment by ctb** [comment]
maybe one readme to rule them all in the folder above them, with links
and descriptions into the subfolders?

thx

On Fri, Mar 08, 2019 at 11:42:01AM -0800, Taylor Reiter wrote:
> There are READMEs in each subfolder of pipeline analyses that layout what each workflow does...would you like this organized differently?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/spacegraphcats/2018-paper-spacegraphcats/pull/9#issuecomment-471051708
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by ctb** [comment]
done!

**Pull request merged**
