### PR TITLE
Merge #12 into revisions branch instead of master

### PR DESCRIPTION
**Pull request by ctb**

### CODE REVIEW

**Comment by ctb** [comment]
@taylorreiter thank you! a couple of questions --

* what are the correct units (if any) for contamination and strain heterogeneity?
* what do you think about calling it "redundancy" instead of "contamination" ? :)
* can you add the relevant units ('%', etc.) appropriately, as in Table 7?
* what order do you think the results should be presented in ? I'm thinking it would be good to have it be in the same order as in table 7.

also if you could re-forward me the e-mail with details of how redundancy etc are calculated, I'd appreciate it :)

**Comment by taylorreiter** [comment]
+ what are the correct units (if any) for contamination and strain heterogeneity?
Percent
+ what do you think about calling it "redundancy" instead of "contamination" ? :)
I'm ok with this, but it might obscure the measure from checkmophiles (although I think it makes our message more clear)
+ can you add the relevant units ('%', etc.) appropriately, as in Table 7?
Sure!
+ what order do you think the results should be presented in ? I'm thinking it would be good to have it be in the same order as in table 7.
I think right now it is in hu-genome19, hu-genome20...etc., I can put it in the same order as table 7!

forwarded :)

**Comment by ctb** [comment]
another minor request - could you adjust the numbers for completeness, redundancy, and strain heterogeneity, in the two new tables to have only 1 significant fractional digit, please?

Also, what do you think about adding another table with all of the plass-assembled bin information, for the not-kmer-trimmed neighborhoods? I'm still struggling with the variety of information we have to present :)

**Comment by ctb** [comment]
merging latest in, minor adjustments can be a new PR.

**Pull request merged**
